### PR TITLE
Ziyaad branch

### PR DESCRIPTION
**Pull request by ZiyaadLakay**
Updated Design and database

### CODE REVIEW

**Comment by jeanluciradukunda** [comment]
Please for future reference, give your branches more meaningful and specific names. 🙏🏾

**Comment by jeanluciradukunda** [comment]
... and your description needs to be more detailed so that the person reviewing the code knows what exactly they’re looking at and looking for.

**Comment by ZiyaadLakay** [comment]
I know, but this branch was not deleted in the last pull so i didnt wanna keep making new branches, and the stuff i updated was lining up the icons so it looked more centered

**Comment by jeanluciradukunda** [comment]
Coolio. You can manually delete branches, by going to the branch on github. To delete local branch ‘git branch -D branch_name’

**Pull request merged**
